parameters:
#    frontend_web.example.class: SearchAwesome\WebBundle\Example

services:
#    frontend_web.example:
#        class: %frontend_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
