tags:
    type:       rest
    resource:   SearchAwesome\ApiBundle\Controller\TagController

icons:
    type:       rest
    resource:   SearchAwesome\ApiBundle\Controller\IconController

sites:
    type:       rest
    resource:   SearchAwesome\ApiBundle\Controller\SiteController

post_tag:
    pattern:    /tags.{_format}
    defaults: { _controller: SearchAwesomeApiBundle:Tag:post, _format: 'json' }
    requirements: { _format: 'json' }
    methods: [ 'POST' ]

post_icon_tag:
    pattern:    /icons/{id}/tags.{_format}
    defaults: { _controller: SearchAwesomeApiBundle:Icon:postTag, _format: 'json' }
    requirements: { _format: 'json', id: "[a-z0-9]+" }
    methods: [ 'POST' ]

login_status:
    pattern:    /login_status
    defaults: { _controller: SearchAwesomeApiBundle:Login:loginStatus, _format: 'json' }
    requirements: { _format: 'json' }
    methods: [ 'POST' ]
