imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    globals:
        recaptcha_public_key: %recaptcha_public_key%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'SearchAwesomeWebBundle' ]
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [%node_modules%]
            apply_to: "\.less$"
        coffee:
            bin: %coffee_path%
            node: %node_path%
            apply_to: "\.coffee$"
        sass:
            bin: %sass_path%
            apply_to: "\.scss$"
        uglifyjs2:
            bin: %uglify_js%
            node: %node_path%
        uglifycss:
            bin: %uglify_css%
            node: %node_path%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongo_host%:%mongo_port%/%mongo_database%
            options: {}
    default_database: %mongo_database%
    document_managers:
        default:
            auto_mapping: true

code_lovers_acl:
    handler:    mongodb

sixdays_opcache:
    host_ip:    %opcache_host_ip%
    host_name:  %app_domain%
    web_dir:    %kernel.root_dir%/../web

iam_persistent_mongo_db_acl:
    acl_provider:
        default_database: %mongo_database%

# JMSTranslationBundle
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs]
            output_format: xliff
            default_output_format: xliff

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

fos_rest:
    view:
        formats:
            rss:    false
            xml:    false
            json:   true
            jsonp:  true
        jsonp_handler: ~
        failed_validation: HTTP_BAD_REQUEST
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
            rss: 'application/rss+xml'
            jpg: 'image/jpeg'
            png: 'image/png'
        view_response_listener: 'force'
#        disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    routing_loader:
        default_format: json
    body_converter:
        enabled:    true
        validate: true
        validation_errors_argument: validationErrors # This is the default value
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
#        messages:
#            'Acme\HelloBundle\Exception\MyExceptionWithASafeMessage': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    serializer:
        groups:     ["REST"]
    service:
        view_handler: backend_api.view_handler

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: SearchAwesome\CoreBundle\Document\User

dunglas_angular_csrf:
    cookie:
        set_on:
            - {path "^/", methods: [GET, POST] }
    secure:
        - { path: "^/api" }
        - { route: "^fos_user_security" }

