frontend_web:
    resource: "@FrontendWebBundle/Resources/config/routing.yml"
    prefix:   /

backend_api:
    type:     rest
    resource: "@BackendApiBundle/Resources/config/routing.yml"
    prefix:   /