frontend_web:
    resource: "@SearchAwesomeWebBundle/Resources/config/routing.yml"
    prefix:   /

backend_api:
    type:     rest
    resource: "@SearchAwesomeApiBundle/Resources/config/routing.yml"
    prefix:   /