<?php

namespace SearchAwesome\CoreBundle\Repository;
use SearchAwesome\CoreBundle\Document\Icon;
use SearchAwesome\CoreBundle\Document\Tag;

/**
 * IconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconRepository extends Repository
{
    /**
     * @param Tag[] $tags
     *
     * @return Icon[]
     */
    public function findByTags($tags)
    {
        $ids = array();

        foreach ($tags as $tag) {
            $ids[] = new \MongoId($tag->getId());
        }

        return $this->createQueryBuilder()
            ->field('tags')->in($ids)
            ->getQuery()
            ->execute()
            ->toArray();
    }
}