<?php

namespace SearchAwesome\CoreBundle\Repository;
use SearchAwesome\CoreBundle\Document\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends Repository
{
    /**
     * @param string $search
     *
     * @return Tag[]
     */
    public function findByName($search)
    {
        $regexes = array();

        foreach (explode(' ', $search) as $s) {
            if (trim($s)) {
                $regexes[] = new \MongoRegex('/' . $s . '/i');
            }
        }
        return $this->createQueryBuilder()
            ->field('name')->in($regexes)
            ->getQuery()
            ->execute()
            ->toArray();
    }
}