<?php

namespace SearchAwesome\CoreBundle\Repository;
use SearchAwesome\CoreBundle\Document\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends Repository
{
    /**
     * @param string $search
     *
     * @return Tag[]
     */
    public function findByName($search)
    {
        return $this->createQueryBuilder()
            ->field('name')->equals(new \MongoRegex('/' . $search . '/'))
            ->getQuery()
            ->execute()
            ->toArray();
    }
}