parameters:
    backend_core.manager.tag.class: Backend\CoreBundle\Manager\TagManager
    backend_core.manager.site.class: Backend\CoreBundle\Manager\SiteManager
    backend_core.manager.icon.class: Backend\CoreBundle\Manager\IconManager

services:
    backend_core.manager.tag:
        class: %backend_core.manager.tag.class%
        arguments: [@doctrine.odm.mongodb.document_manager]

    tag_manager:
        alias: backend_core.manager.tag

    backend_core.manager.site:
        class: %backend_core.manager.site.class%
        arguments: [@doctrine.odm.mongodb.document_manager]

    site_manager:
        alias: backend_core.manager.site

    backend_core.manager.icon:
        class: %backend_core.manager.icon.class%
        arguments: [@doctrine.odm.mongodb.document_manager]

    icon_manager:
        alias: backend_core.manager.icon

