<?php

namespace Backend\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * IconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconRepository extends DocumentRepository
{
}