Backend\CoreBundle\Document\Tag:
    repositoryClass:    Backend\CoreBundle\Repository\TagRepository
    collection:         tags

    indexes:
        name:
            keys:
                name: true
            options:
                background: true
                unique: true
        soundex:
            keys:
                soundex: true
            options:
                background: true

    referenceMany:
        icons:
            targetDocument: Backend\CoreBundle\Document\Icon
            mappedBy:   tags

    fields:
        id:
            id: true
        name:
            type: string
        versions:
            type: collection
        cssClass:
            type: string
        soundex:
            type: string

