SearchAwesome\CoreBundle\Document\Icon:
    repositoryClass:    SearchAwesome\CoreBundle\Repository\IconRepository
    collection:         icons
    type:               document

    indexes:
        tags:
            keys:
                tags: true
            options:
                background: true
        site_name:
            keys:
                site: true
                name: true
            options:
                background: true
                unique: true

    referenceOne:
        site:
            targetDocument: SearchAwesome\CoreBundle\Document\Site
            index:  true
            simple: true
            inversedBy: icons

    embedMany:
        tags:
            targetDocument: SearchAwesome\CoreBundle\Document\TagUsage
            index:  true
            simple: true

    fields:
        id:
            id: true
        name:
            type: string
        versions:
            type: collection
        aliases:
            type: collection
        cssClass:
            type: string
        created_at:
            type: date
        updated_at:
            type: date
        unicode:
            type: string

    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]

