SearchAwesome\CoreBundle\Document\Tag:
    repositoryClass:    SearchAwesome\CoreBundle\Repository\TagRepository
    collection:         tags
    type:               document

    indexes:
        name:
            keys:
                name: true
            options:
                background: true
                unique: true
        soundex:
            keys:
                soundex: true
            options:
                background: true

    fields:
        id:
            id: true
        name:
            type: string
        soundex:
            type: string
        created_at:
            type: date
        updated_at:
            type: date

    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]