SearchAwesome\CoreBundle\Document\TagUsage:
    collection:         sites
    type:               embeddedDocument

    indexes:
        deleted:
            keys:
                deleted: 1
        validated:
            keys:
                validated: 0

    fields:
        name:
            type: string
        soundex:
            type: string
        tagId:
            type: id
        validated:
            type: boolean
        deleted:
            type: boolean

    referenceOne:
        tag:
            targetDocument: SearchAwesome\CoreBundle\Document\Tag
            simple: true

